### PR TITLE
Fix example for naming app

### PR DESCRIPTION
**Pull request by xarisd**
According to recommendation the name should be `roo-it-production`.

It also contains some automatic removal of whitespace at the end of the lines. 
Please give some feedback on what is the general approach for this (whitespace removal and code formatting in general).

### CODE REVIEW

**Comment by xarisd** [comment]
Thanks!

**Comment by kapowaz** [comment]
Whitespace removal is always a good thing, btw. It’d be great if use of automatic whitespace-removal tools were recommended, but as far as I‘m aware there’s no widespread approach for that — just individual developers using whatever works.

**Comment by xarisd** [comment]
We could use something like http://editorconfig.org/ to (try to) "enforce" it in non-critical repositories/projects such as this one.

Like, including a `.editorconfig` in the project root.

This way we will be lowering the barrier because most of the editors/IDEs has support for that.

Should I open an issue for this? Just to investigate what everyone thinks?

**Comment by kapowaz** [comment]
Go for it — definitely worth getting the conversation started. I’m pretty sure people have discussed using `.editorconfig` for similar things in the past.

**Pull request merged**
